### ISSUE TITLE
バグ報告　リリースモード時でのエンディングに移動するとフリーズ

### ISSUE THREAD

**Issue by suberidai** [KitchenKnife/SDP#3]
リリースモードにてゲームシーンからエンディングシーンへ移行すると遷移後にフリーズする。
Sバグなので修正よろしく♡

**Comment by whuchan** [comment]
原因：
CGameMainでのメモリの解放忘れと、
アプリケーション終了時のメモリ解放し忘れ
cocos2dの仕様の問題で、addChild（）したメモリは全てremoveFromParent()で解放する。
deleteしてはいけない。

改善案
シングルトン多様するのはいいけど、必ず解放すること
